apiVersion: v1
kind: Service
metadata:
        name: svc-nsx-demo
        labels:
                app: nsx-demo
spec:
        ports:
                - port: 80
                  targetPort: 5000
        selector:
                app: nsx-demo
        type: LoadBalancer
