apiVersion: extensions/v1beta1
kind: Ingress
metadata:
        name: ingress-nsx-demo
        annotations:
          ncp/use-regex: "true"
spec:
        rules:
        - host: nsx-demo.corp.local
          http:
            paths:
            - path: /.*
              backend:
                serviceName: svc-nsx-demo
                servicePort: 80

       

