# using new api version
# using regex to rewrite from frontend path /nsx-demo to backend path /
# /scan url doesnt work here

apiVersion:  networking.k8s.io/v1 
kind: Ingress
metadata:
        name: nsx-demo
        annotations:
          ncp/use-regex: "true"
          ingress.kubernetes.io/rewrite-target: /$2
spec:
        rules:
        - host: tanzudemo.app.corp.local
          http:
            paths:
            - path: /nsx-demo(/|$)(.*)
              pathType: ImplementationSpecific
              backend:
                service:
                   name: nsx-demo
                   port: 
                     number: 80

       

